### PR TITLE
feat: Allow extend function from external

### PR DESCRIPTION
**Pull request by Shawnyeungcf**
Should allow dev to extend the publish and consume method to custom behavior. 

In more steps, should let user set the specific exchange or queue when creating class.

### CODE REVIEW

**Review by blumamir — APPROVED** [review]
can't completely understand the motivation, but if it helps you in any way then it LGTM

**Comment by blumamir** [comment]
merged this change into master. do you need it published now? or can it wait for the next release?

**Comment by Shawnyeungcf** [comment]
> merged this change into master. do you need it published now? or can it wait for the next release?

Yes, please pub 👍

**Comment by blumamir** [comment]
@Shawnyeungcf - I thought I published it, but now I see that it might have not been completed successfully. 
Anyhow, It should be published now. Hope I didn't cause any problems to you

**Pull request merged**
